[package]
name = "algo-consensus-crypto"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
algo-falcon.workspace = true
algo-types.workspace = true
curve25519-dalek.workspace = true
ed25519-dalek.workspace = true
serde.workspace = true
serde_bytes.workspace = true
sha2.workspace = true
sha3.workspace = true
thiserror.workspace = true
rand.workspace = true
rmp.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
statrs.workspace = true
zeroize.workspace = true
scrypt.workspace = true

[dev-dependencies]
hex.workspace = true
serde_json.workspace = true
rand_chacha = "0.3"
