[package]
name = "algo-ledger"
version = "0.1.0"
edition = "2021"

[dependencies]
algo-types = { workspace = true }
algo-error = { workspace = true }
algo-avm = { workspace = true }
algo-codec = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_bytes = { workspace = true }
data-encoding = { workspace = true }
rmpv = { workspace = true }
rmp-serde = { workspace = true }
rmp = { workspace = true }
rusqlite = { workspace = true }
sha2 = { workspace = true }
tracing = { workspace = true }
