//! AVM/TEAL opcode conformance harness (Rust AVM vs go-algorand logic eval).
//!
//! Consumes the JSONL corpus captured by `tools/avm-opcode-capture` and, for
//! every fixture {program, args, proto}, runs the program through the Rust
//! AVM as a LogicSig and asserts the result matches go-algorand's
//! authoritative `logic.EvalSignatureFull` output:
//!
//!   - **error category**: errored vs. did-not-error (go and Rust error
//!     *strings* differ — go embeds `pc=`/`Details:` — so matching the
//!     boolean errored category is what is meaningful).
//!   - **pass**: program-approved flag (only when neither side errored).
//!   - **final stack**: value-for-value, bottom-to-top (only when neither
//!     side errored).
//!
//! This is the opcode-level coverage that was MISSING when BT-294 (a
//! consensus-critical `ed25519verify` divergence — the Rust op
//! SHA-512/256-prehashed the `"ProgData"||H(Program)||data` payload that go
//! does NOT prehash) shipped undetected. The `ed25519verify/valid` fixture
//! carries a go-produced signature over the raw payload; the pre-fix Rust op
//! would have REJECTED it, so a passing replay here proves the fix and would
//! have caught the original bug.
//!
//! Fixture: `tests/fixtures/avm/vectors.jsonl` (generated by the capture
//! tool). See the sibling `fixtures/avm/README.md` for the record schema and
//! regeneration procedure.
//!
//! References (go-algorand v4.6.0-stable):
//!   - `data/transactions/logic/eval.go:1228`  — `EvalSignatureFull`
//!   - `data/transactions/logic/crypto.go:175` — `opEd25519Verify` (BT-294 site)
//!   - `data/transactions/logic/crypto.go:162` — `Msg.ToBeHashed`

use std::fs::File;
use std::io::{BufRead, BufReader};
use std::path::PathBuf;

use algo_avm::{parse, AvmMachine, AvmValue, ExecMode, LogicSigAvmContext};
use algo_types::consensus::consensus_params_for_version;
use algo_types::SignedTransaction;
use serde::Deserialize;

/// One final-stack slot as recorded by the Go capture tool.
#[derive(Debug, Deserialize)]
struct StackEntry {
    /// "u" = uint64, "b" = bytes.
    t: String,
    /// Decimal string for uint64, hex for bytes.
    v: String,
}

/// One JSONL record from `vectors.jsonl`. Field names mirror the Go capture
/// tool's `Vector` struct exactly.
#[derive(Debug, Deserialize)]
struct Record {
    name: String,
    #[allow(dead_code)]
    description: String,
    proto: String,
    program: String,
    args: Vec<String>,
    pass: bool,
    /// Empty iff go returned no error.
    error: String,
    /// Absent / null when go errored (omitempty in the capture tool).
    #[serde(default, deserialize_with = "null_as_empty")]
    final_stack: Vec<StackEntry>,
    /// False for programs that halt via an explicit `return` (residual stack
    /// is implementation-defined). When false, only (errored, pass) is
    /// compared, not the final stack.
    compare_stack: bool,
}

/// Deserialize a JSON `null` final_stack (go's omitempty on the error path)
/// as an empty vector.
fn null_as_empty<'de, D>(de: D) -> Result<Vec<StackEntry>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    Ok(Option::<Vec<StackEntry>>::deserialize(de)?.unwrap_or_default())
}

fn fixture_path() -> PathBuf {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("tests/fixtures/avm/vectors.jsonl");
    p
}

fn decode_hex(name: &str, field: &str, s: &str) -> Vec<u8> {
    hex::decode(s)
        .unwrap_or_else(|e| panic!("fixture {name:?}: {field} is not valid hex: {e} (value={s:?})"))
}

/// Run a LogicSig program (with args) through the Rust AVM, returning
/// `Ok((pass, final_stack))` on success or `Err(message)` on a hard AVM error
/// — mirroring `algo_avm::run_logicsig_program` but keeping the machine so the
/// final stack can be compared against go's.
fn run_rust(
    name: &str,
    program: &[u8],
    args: Vec<Vec<u8>>,
    proto: &str,
) -> Result<(bool, Vec<AvmValue>), String> {
    let consensus = consensus_params_for_version(proto)
        .unwrap_or_else(|| panic!("fixture {name:?}: unknown consensus version {proto:?}"));

    // Single-element group with a default transaction. The fixture programs
    // reference only `arg`, crypto-verify, and arithmetic opcodes — none read
    // txn/group fields — so a default txn is sufficient. The LogicSig context
    // supplies `arg`, `program_hash()` (SHA-512/256("Program" || program),
    // matching go's `crypto.HashObj(Program(program))`), and the consensus
    // `logic_sig_version` ceiling.
    let group: Vec<SignedTransaction> = vec![SignedTransaction::default()];

    // Pre-eval version ceiling check (matches run_logicsig_program /
    // go-algorand's eval.go pre-eval check).
    let ceiling = consensus.logic_sig_version;
    if let Some(&version) = program.first() {
        if u64::from(version) > ceiling {
            return Err(format!(
                "program version {version} greater than protocol supported version {ceiling}"
            ));
        }
    }

    let mut ctx = LogicSigAvmContext::new(&group, 0, program, args, consensus);

    let parsed = parse(program).map_err(|e| e.to_string())?;
    let budget = algo_avm::LOGICSIG_BUDGET;
    let mut machine = AvmMachine::new(parsed, ExecMode::LogicSig, budget);
    match machine.run(&mut ctx) {
        Ok(pass) => Ok((pass, machine.stack.clone())),
        Err(e) => Err(e.to_string()),
    }
}

/// Format a Rust stack value the same way the Go fixture records it, so the
/// two can be compared directly.
fn rust_value_repr(v: &AvmValue) -> (String, String) {
    match v {
        AvmValue::Uint64(u) => ("u".to_string(), u.to_string()),
        AvmValue::Bytes(b) => ("b".to_string(), hex::encode(b)),
    }
}

#[test]
fn avm_opcode_conformance_vs_go_algorand() {
    let path = fixture_path();
    let file = File::open(&path).unwrap_or_else(|e| {
        panic!(
            "cannot open AVM opcode fixture {path:?}: {e}.\n\
             Run `cd tools/avm-opcode-capture && go run .` to regenerate \
             (see docs/DEV_WORKFLOW.md → AVM Opcode Vector Regeneration)."
        )
    });

    let mut total = 0usize;
    let mut crypto_verify_seen = 0usize;
    let mut bt294_guard_passed = false;

    for (line_no, line) in BufReader::new(file).lines().enumerate() {
        let line = line.expect("read fixture line");
        if line.trim().is_empty() {
            continue;
        }
        let rec: Record = serde_json::from_str(&line).unwrap_or_else(|e| {
            panic!("fixture parse error at line {line_no}: {e}\n  raw: {line}")
        });

        let program = decode_hex(&rec.name, "program", &rec.program);
        let args: Vec<Vec<u8>> = rec
            .args
            .iter()
            .map(|a| decode_hex(&rec.name, "arg", a))
            .collect();

        let go_errored = !rec.error.is_empty();
        let result = run_rust(&rec.name, &program, args, &rec.proto);

        match (&result, go_errored) {
            // Both errored: error category matches. We do NOT compare error
            // strings (go embeds pc=/Details:, Rust does not).
            (Err(_), true) => {}
            // Both succeeded: compare pass + final stack.
            (Ok((rust_pass, rust_stack)), false) => {
                assert_eq!(
                    *rust_pass, rec.pass,
                    "AVM divergence in {:?}: go pass={}, rust pass={}\n  {}",
                    rec.name, rec.pass, rust_pass, rec.description
                );

                // Compare the final stack only when it is meaningful — i.e.
                // not for programs that halt via an explicit `return`, where
                // the residual stack is implementation-defined.
                if rec.compare_stack {
                    assert_eq!(
                        rust_stack.len(),
                        rec.final_stack.len(),
                        "AVM stack-length divergence in {:?}: go={} entries, rust={} entries\n  \
                         go_stack types={:?}\n  rust_stack={:?}\n  {}",
                        rec.name,
                        rec.final_stack.len(),
                        rust_stack.len(),
                        rec.final_stack.iter().map(|e| &e.t).collect::<Vec<_>>(),
                        rust_stack,
                        rec.description
                    );

                    for (i, (go_e, rust_v)) in
                        rec.final_stack.iter().zip(rust_stack.iter()).enumerate()
                    {
                        let (rt, rv) = rust_value_repr(rust_v);
                        assert!(
                            rt == go_e.t && rv == go_e.v,
                            "AVM stack[{i}] divergence in {:?}: go={{t:{:?},v:{:?}}}, \
                             rust={{t:{:?},v:{:?}}}\n  {}",
                            rec.name,
                            go_e.t,
                            go_e.v,
                            rt,
                            rv,
                            rec.description
                        );
                    }
                }
            }
            // Error-category divergence: this is exactly the class of bug the
            // harness exists to catch. Fail loudly.
            (Ok((rust_pass, rust_stack)), true) => {
                panic!(
                    "AVM error-category divergence in {:?}: go ERRORED ({:?}) but \
                     rust SUCCEEDED (pass={rust_pass}, stack={rust_stack:?})\n  {}",
                    rec.name, rec.error, rec.description
                );
            }
            (Err(rust_err), false) => {
                panic!(
                    "AVM error-category divergence in {:?}: go SUCCEEDED (pass={}) but \
                     rust ERRORED ({rust_err:?})\n  {}",
                    rec.name, rec.pass, rec.description
                );
            }
        }

        if rec.name.starts_with("ed25519verify")
            || rec.name.starts_with("ecdsa_verify")
            || rec.name.starts_with("vrf_verify")
        {
            crypto_verify_seen += 1;
        }
        // The specific BT-294 guard: a go-signed sig over the raw ProgData
        // payload that the pre-fix Rust op would have rejected. It MUST pass.
        if rec.name == "ed25519verify/valid" {
            assert!(
                matches!(result, Ok((true, _))),
                "BT-294 guard FAILED: {:?} must pass (go-signed over raw \
                 \"ProgData\"||H||data); got {result:?}",
                rec.name
            );
            bt294_guard_passed = true;
        }

        total += 1;
    }

    assert!(
        bt294_guard_passed,
        "BT-294 guard fixture (ed25519verify/valid) is missing from the corpus"
    );
    assert!(
        crypto_verify_seen >= 9,
        "crypto-verify coverage unexpectedly thin ({crypto_verify_seen} vectors); \
         regenerate via `cd tools/avm-opcode-capture && go run .`"
    );
    assert!(
        total >= 15,
        "AVM opcode fixture is unexpectedly small ({total} records); regenerate \
         via `cd tools/avm-opcode-capture && go run .`."
    );

    eprintln!(
        "avm_opcode_conformance_vs_go_algorand: {total} vectors matched go-algorand \
         ({crypto_verify_seen} crypto-verify; BT-294 guard PASSED)"
    );
}
