[package]
name = "algo-avm"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
algo-codec.workspace = true
algo-consensus-crypto.workspace = true
algo-error.workspace = true
algo-falcon.workspace = true
algo-types.workspace = true
num-bigint.workspace = true
sha2.workspace = true
sha3.workspace = true
base64.workspace = true
serde_json.workspace = true
ed25519-dalek.workspace = true
curve25519-dalek.workspace = true
k256.workspace = true
p256.workspace = true

ark-ff.workspace = true
ark-ec.workspace = true
ark-bn254.workspace = true
ark-bls12-381.workspace = true
ark-serialize.workspace = true
data-encoding.workspace = true
serde.workspace = true

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }


[[bench]]
name = "avm_bench"
harness = false
