[package]
name = "goal-rust"
version = "0.1.0"
edition = { workspace = true }
rust-version = { workspace = true }

[[bin]]
name = "goal-rust"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
algo-rest-client = { workspace = true }
algo-error = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
tempfile = "3"
