[package]
name = "algo-p2p"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
libp2p = { version = "0.54", features = [
    "tcp",
    "noise",
    "yamux",
    "tokio",
] }
tokio.workspace = true
thiserror.workspace = true
futures-util.workspace = true
void = "1"
