[package]
name = "algo-types"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[features]
fuzzing = ["arbitrary"]

[dependencies]
algo-error.workspace = true
serde.workspace = true
rmp.workspace = true
rmpv.workspace = true
hex.workspace = true
serde_bytes.workspace = true
data-encoding.workspace = true
sha2 = { workspace = true }
arbitrary = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
serde_json.workspace = true
rmp-serde.workspace = true
