//! Byte-exact VRF parity harness (Rust vs go-algorand / libsodium-fork).
//!
//! Consumes the JSONL corpus captured by `tools/vrf-vector-capture` and
//! asserts that, for every (seed, alpha) tuple, Rust's pure-Rust
//! ECVRF-ED25519-SHA512-Elligator2 impl produces **byte-identical**
//! proof / output / verify behaviour.
//!
//! This is consensus-critical: a single byte of divergence in a proof would
//! cause committee-selection disagreement and a hard fork. On any mismatch
//! the test fails LOUDLY with enough context to diagnose the divergence
//! without re-running the capture tool:
//!
//!   - fixture `name`
//!   - full seed / alpha / go-proof / rust-proof in hex
//!   - first diverging byte offset (so a single-bit flip is obvious)
//!
//! Fixture: `tests/fixtures/vrf/vectors.jsonl` (generated by the capture
//! tool; 10,198 vectors in the initial corpus). See the sibling
//! `fixtures/vrf/README.md` for the record schema and regeneration
//! procedure.
//!
//! References (go-algorand v4.6.0-stable):
//!   - `crypto/vrf.go:99`  — `C.crypto_vrf_prove`
//!   - `crypto/vrf.go:117` — `C.crypto_vrf_proof_to_hash`
//!   - `crypto/vrf.go:122` — `C.crypto_vrf_verify`
//!
//! Budget target: <30s for 10K+ tuples on a modern x86_64 laptop.

use std::fs::File;
use std::io::{BufRead, BufReader};
use std::path::PathBuf;

use algo_consensus_crypto::vrf::{VrfPrivkey, VrfProof, VrfPubkey};
use serde::Deserialize;

/// One JSONL record from `vectors.jsonl`. Field names mirror the Go
/// capture tool's `Vector` struct exactly.
#[derive(Debug, Deserialize)]
struct Record {
    name: String,
    seed: String,
    alpha: String,
    pk: String,
    sk: String,
    proof: String,
    output: String,
}

fn fixture_path() -> PathBuf {
    // tests/ is the crate root for integration tests, so Cargo sets
    // CARGO_MANIFEST_DIR to the crate's Cargo.toml directory.
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("tests/fixtures/vrf/vectors.jsonl");
    p
}

fn decode_hex(field: &str, s: &str) -> Vec<u8> {
    hex::decode(s)
        .unwrap_or_else(|e| panic!("fixture: {field} is not valid hex: {e} (value={s:?})"))
}

/// Compare two byte slices; on mismatch, format a diagnostic pinpointing
/// the first diverging byte offset. Returns `None` when they match.
fn first_diff(go: &[u8], rust: &[u8]) -> Option<usize> {
    if go.len() != rust.len() {
        return Some(go.len().min(rust.len()));
    }
    for (i, (a, b)) in go.iter().zip(rust.iter()).enumerate() {
        if a != b {
            return Some(i);
        }
    }
    None
}

/// Panic with a divergence report containing everything needed to reproduce
/// the failure: fixture name, seed, alpha, expected/actual hex, first
/// mismatched byte offset.
#[track_caller]
fn fail_divergence(
    rec: &Record,
    what: &str,
    go_bytes: &[u8],
    rust_bytes: &[u8],
    first_diff_idx: usize,
) -> ! {
    panic!(
        "VRF parity divergence in {what} for fixture {name:?}\n  \
         seed   = {seed}\n  \
         alpha  = {alpha} ({alpha_len} bytes)\n  \
         pk     = {pk}\n  \
         go     = {go_hex}\n  \
         rust   = {rust_hex}\n  \
         first diverging byte offset: {offset} \
         (go[{offset}] = {go_byte:#04x}, rust[{offset}] = {rust_byte:#04x})",
        name = rec.name,
        seed = rec.seed,
        alpha = rec.alpha,
        alpha_len = rec.alpha.len() / 2,
        pk = rec.pk,
        go_hex = hex::encode(go_bytes),
        rust_hex = hex::encode(rust_bytes),
        offset = first_diff_idx,
        go_byte = go_bytes.get(first_diff_idx).copied().unwrap_or(0),
        rust_byte = rust_bytes.get(first_diff_idx).copied().unwrap_or(0),
    );
}

/// Iterate every fixture and assert byte-exact parity on prove / hash /
/// verify against the captured Go output.
///
/// ## Debug vs release scope
///
/// Rust's pure-Rust VRF is ~100× slower in unoptimised builds: the full
/// 10K-vector sweep takes ~8 minutes in `cargo test` (debug) but ~4
/// seconds in `cargo test --release`. Running the entire sweep every
/// time a developer does `cargo test --workspace` would make the local
/// test flow unusable, so in debug builds we iterate only the ~198
/// fixed edge-case entries (`fixed/…` names) — enough to catch
/// regressions in TV1/TV2 and the named edge cases. Release builds
/// (including CI) iterate every record. The `AVR_FULL=1` env var
/// forces the full sweep in debug mode for when a developer wants to
/// reproduce a CI failure locally.
#[test]
fn vrf_parity_vs_go_algorand() {
    let path = fixture_path();
    let file = File::open(&path).unwrap_or_else(|e| {
        panic!(
            "cannot open VRF fixture {path:?}: {e}.\n\
             Run `cd tools/vrf-vector-capture && go run .` to regenerate \
             (see docs/DEV_WORKFLOW.md → VRF Vector Regeneration)."
        )
    });

    let full_sweep = !cfg!(debug_assertions) || std::env::var_os("AVR_FULL").is_some();

    let mut total = 0usize;
    let mut skipped = 0usize;
    for (line_no, line) in BufReader::new(file).lines().enumerate() {
        let line = line.expect("read fixture line");
        if line.is_empty() {
            continue;
        }
        let rec: Record = serde_json::from_str(&line).unwrap_or_else(|e| {
            panic!("fixture parse error at line {line_no}: {e}\n  raw: {line}")
        });

        if !full_sweep && !rec.name.starts_with("fixed/") {
            skipped += 1;
            continue;
        }

        let seed_bytes = decode_hex("seed", &rec.seed);
        let alpha = decode_hex("alpha", &rec.alpha);
        let pk_bytes = decode_hex("pk", &rec.pk);
        let go_proof = decode_hex("proof", &rec.proof);
        let go_output = decode_hex("output", &rec.output);

        assert_eq!(
            seed_bytes.len(),
            32,
            "fixture {:?}: seed must be 32 bytes",
            rec.name
        );
        assert_eq!(
            pk_bytes.len(),
            32,
            "fixture {:?}: pk must be 32 bytes",
            rec.name
        );
        assert_eq!(
            go_proof.len(),
            80,
            "fixture {:?}: proof must be 80 bytes",
            rec.name
        );
        assert_eq!(
            go_output.len(),
            64,
            "fixture {:?}: output must be 64 bytes",
            rec.name
        );
        // sk is 64 bytes (ed25519 seed || pk) and is recorded for
        // debuggability, not exercised on the Rust side — Rust's
        // VrfPrivkey is the 32-byte seed form.
        assert_eq!(
            rec.sk.len() / 2,
            64,
            "fixture {:?}: sk must be 64 bytes",
            rec.name
        );

        // 1. Derived pk must match the captured pk (guards against seed
        //    clamping / base-mul drift independent of prove).
        let seed_arr: [u8; 32] = seed_bytes
            .as_slice()
            .try_into()
            .expect("checked length above");
        let sk = VrfPrivkey::from_seed(seed_arr);
        let derived_pk = sk.pubkey();
        let pk_arr: [u8; 32] = pk_bytes
            .as_slice()
            .try_into()
            .expect("checked length above");
        if derived_pk.0 != pk_arr {
            if let Some(off) = first_diff(&pk_bytes, &derived_pk.0) {
                fail_divergence(&rec, "pubkey derivation", &pk_bytes, &derived_pk.0, off);
            }
        }

        // 2. prove: Rust proof byte-identical to Go proof.
        let (rust_proof, rust_output) = sk.prove(&alpha);
        if rust_proof.0.as_slice() != go_proof.as_slice() {
            let off = first_diff(&go_proof, &rust_proof.0).expect("lens differ or all match");
            fail_divergence(&rec, "prove", &go_proof, &rust_proof.0, off);
        }

        // 3. proof.to_hash: Rust output byte-identical to Go output.
        let rust_hash = rust_proof.to_hash().unwrap_or_else(|| {
            panic!(
                "fixture {:?}: Rust VrfProof::to_hash returned None",
                rec.name
            )
        });
        if rust_hash.0.as_slice() != go_output.as_slice() {
            let off = first_diff(&go_output, &rust_hash.0).expect("lens differ or all match");
            fail_divergence(&rec, "proof.to_hash", &go_output, &rust_hash.0, off);
        }
        // And prove's returned output must equal to_hash's output (internal
        // consistency; a divergence here would indicate the Rust impl is
        // producing two different hashes for the same proof).
        assert_eq!(
            rust_output.0, rust_hash.0,
            "fixture {:?}: prove().1 != proof.to_hash()",
            rec.name
        );

        // 4. verify: Rust accepts Go's proof against the captured pk and
        //    returns the exact same output. This closes the "prove matches
        //    but verify doesn't" failure mode — e.g. a drift in the verify
        //    challenge recomputation.
        let go_proof_arr: [u8; 80] = go_proof
            .as_slice()
            .try_into()
            .expect("checked length above");
        let go_proof_ty = VrfProof(go_proof_arr);
        let rust_verify = VrfPubkey(pk_arr)
            .verify(&go_proof_ty, &alpha)
            .unwrap_or_else(|| {
                panic!(
                    "fixture {:?}: Rust verify REJECTED a Go-accepted proof\n  \
                     seed={seed} alpha={alpha}",
                    rec.name,
                    seed = rec.seed,
                    alpha = rec.alpha,
                )
            });
        if rust_verify.0.as_slice() != go_output.as_slice() {
            let off = first_diff(&go_output, &rust_verify.0).expect("lens differ or all match");
            fail_divergence(&rec, "verify(Go proof)", &go_output, &rust_verify.0, off);
        }

        total += 1;
    }

    // Sanity floor: the committed corpus is ≥10K entries (~198 fixed +
    // ~10,000 random). A truncated fixture would quietly reduce coverage
    // without obviously breaking anything, so guard against that.
    if full_sweep {
        assert!(
            total >= 10_000,
            "VRF parity fixture is unexpectedly small ({total} records). \
             Regenerate via `cd tools/vrf-vector-capture && go run .`."
        );
    } else {
        assert!(
            total >= 100,
            "VRF parity fixed-edge-case subset is unexpectedly small ({total}). \
             Regenerate the corpus."
        );
    }
    eprintln!(
        "vrf_parity_vs_go_algorand: {total} vectors matched byte-for-byte \
         (skipped {skipped} random entries in debug mode; set AVR_FULL=1 \
         to force the full sweep)"
    );
}
