#!/usr/bin/env python3
# Copyright (c) 2026 Algod DAO
# SPDX-License-Identifier: MIT
# See the LICENSE-MIT file in the repository root for the full license text.

"""Deterministic "rich" workload driver for the mixed-cluster soak (issue #1674).

The plain soak (soak.sh) submits nothing, so every block it observes is
empty.  That says nothing about the Execute-mode follow path (#1665) or the
stricter minimum-balance sweep (#1660).  This driver submits a seeded mix of
transactions through the go-algorand `goal` CLI running inside the Go node
container, and records every step in a JSONL file that analyze.py and
blockcompare.py consume:

  payments, exact-min-balance payments, ASA create / opt-in / transfer /
  freeze / clawback / close-out / destroy, application create / call /
  opt-in / close-out / clear / delete, boxes (put, create, get, extract,
  replace, splice, resize, delete), inner payment / asset create / asset
  transfer / asset close / app create / app call / app delete, an
  app-account close through an inner payment with close_remainder_to,
  atomic groups, account closes, and transactions that MUST be rejected
  (closing an account that still holds assets, spending below the minimum
  balance, a frozen transfer, a failing box assert, an app-account close
  with assets).  Negative transactions are signed with goal and submitted
  to BOTH a Go node and the Rust node over REST so the two admission paths
  are compared too.

The *schedule* (which scenario runs when, with which parameters) is a pure
function of --seed.  Account keys are generated by kmd and therefore differ
between runs, so txids differ; the schedule does not.

This script never starts or stops the cluster.  It needs the cluster from
start.sh, Docker on PATH, and python3 (standard library only).

Usage:
  workload.py --out workload.jsonl [--seed N] [--rounds N] [--duration-s S]
"""

import argparse
import base64
import hashlib
import json
import os
import random
import re
import signal
import subprocess
import sys
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
WORKLOAD_DIR = os.path.join(ROOT, "workload")

GO_CONTAINER = "phase6-go-node-1"
DATA_DIR = "/algod/data"
WORK_DIR = "/tmp/w"
TOKEN = os.environ.get("ALGOD_TOKEN", "a" * 64)
# name -> REST port (matches docker-compose.yml)
NODE_PORTS = {"go-node-1": 4001, "go-node-2": 4002, "go-node-3": 4003, "rust-node-4": 4004}
NEGATIVE_TARGETS = ("go-node-1", "rust-node-4")

TXID_RE = re.compile(r"\b[A-Z2-7]{52}\b")
ADDR_RE = re.compile(r"\b[A-Z2-7]{58}\b")
ROUND_RE = re.compile(r"committed in round (\d+)")
APP_ID_RE = re.compile(r"Created app with app index (\d+)")
ASSET_ID_RE = re.compile(r"Created asset with asset index (\d+)")
NEW_ACCOUNT_RE = re.compile(r"Created new account with address (\S+)")

# Order of the first pass.  Every scenario runs once, in this order, before
# the seeded random mix starts, so even a 20-round smoke covers each op.
# Stop submitting this many rounds before the soak's last round so the final
# step commits inside the compared range.
STOP_MARGIN_ROUNDS = 6

SCENARIO_ORDER = (
    "pay",
    "min_balance",
    "asset",
    "app_boxes",
    "app_inner",
    "app_local",
    "group",
    "account_close",
    "app_close_delete",
)
SCENARIO_WEIGHTS = {
    "pay": 3,
    "min_balance": 2,
    "asset": 2,
    "app_boxes": 2,
    "app_inner": 2,
    "app_local": 1,
    "group": 2,
    "account_close": 1,
    "app_close_delete": 1,
}


def utc_now():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%fZ")


def app_address(app_id: int) -> str:
    """Address of an application account: sha512_256("appID" || be64(id))."""
    pk = hashlib.new("sha512_256", b"appID" + int(app_id).to_bytes(8, "big")).digest()
    chk = hashlib.new("sha512_256", pk).digest()[-4:]
    return base64.b32encode(pk + chk).decode("ascii").rstrip("=")


def parse_goal_output(text: str) -> dict:
    """Extract txids / committed round / created ids from `goal` output."""
    txids = []
    for t in TXID_RE.findall(text):
        if t not in txids:
            txids.append(t)
    m = ROUND_RE.search(text)
    app = APP_ID_RE.search(text)
    asset = ASSET_ID_RE.search(text)
    return {
        "txids": txids,
        "round": int(m.group(1)) if m else None,
        "app_id": int(app.group(1)) if app else None,
        "asset_id": int(asset.group(1)) if asset else None,
    }


def genesis_funder(genesis_path: str):
    """Address of the genesis alloc whose comment is Wallet1, or None."""
    try:
        with open(genesis_path, encoding="utf-8") as f:
            g = json.load(f)
    except (OSError, ValueError):
        return None
    for a in g.get("alloc", []):
        if a.get("comment") == "Wallet1":
            return a.get("addr")
    return None


class ScenarioAbort(Exception):
    """A scenario cannot continue (a prerequisite step failed)."""


class StopRequested(Exception):
    pass


# ── environment ────────────────────────────────────────────────────────


class Env:
    """Everything that touches the outside world.  Tests substitute a fake."""

    def __init__(self, container=GO_CONTAINER, wallet=None):
        self.container = container
        self.wallet = wallet
        self.user = "root"

    def sh(self, cmd: str, timeout=180):
        try:
            p = subprocess.run(
                ["docker", "exec", "-u", self.user, self.container, "sh", "-c", cmd],
                stdin=subprocess.DEVNULL,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                timeout=timeout,
                check=False,
            )
            return p.returncode, p.stdout.decode("utf-8", "replace")
        except subprocess.TimeoutExpired:
            return 124, "timeout after {}s: {}".format(timeout, cmd)

    def goal(self, args: str, timeout=180):
        w = " -w {}".format(self.wallet) if self.wallet else ""
        return self.sh("goal {}{} -d {}".format(args, w, DATA_DIR), timeout)

    def rest_json(self, path: str, node="go-node-1"):
        url = "http://127.0.0.1:{}{}".format(NODE_PORTS[node], path)
        req = urllib.request.Request(url, headers={"X-Algo-API-Token": TOKEN})
        with urllib.request.urlopen(req, timeout=10) as r:
            return json.loads(r.read().decode("utf-8"))

    def post_txn(self, node: str, raw: bytes):
        url = "http://127.0.0.1:{}/v2/transactions".format(NODE_PORTS[node])
        req = urllib.request.Request(
            url,
            data=raw,
            method="POST",
            headers={"X-Algo-API-Token": TOKEN, "Content-Type": "application/x-binary"},
        )
        try:
            with urllib.request.urlopen(req, timeout=15) as r:
                return r.status, r.read().decode("utf-8", "replace")
        except urllib.error.HTTPError as e:
            return e.code, e.read().decode("utf-8", "replace")
        except (urllib.error.URLError, OSError) as e:
            return 0, "connect error: {}".format(e)

    def fetch_file_b64(self, path: str):
        rc, out = self.sh("base64 -w0 {}".format(path))
        return rc, out.strip()

    def put_file(self, local: str, remote: str):
        subprocess.run(
            ["docker", "cp", local, "{}:{}".format(self.container, remote)],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )

    def current_round(self):
        try:
            return int(self.rest_json("/v2/status")["last-round"])
        except Exception:
            return None

    def sleep(self, s):
        time.sleep(s)


# ── the workload ───────────────────────────────────────────────────────


class Workload:
    def __init__(self, env, out, seed, rounds=0, duration_s=0, funder=None, clock=time.time, only=None):
        self.env = env
        self.only = list(only) if only else None
        self.out = out
        self.seed = seed
        self.rng = random.Random(seed)
        self.rounds = rounds
        self.duration_s = duration_s
        self.funder = funder
        self.clock = clock
        self.seq = 0
        self.start_round = None
        self.t0 = clock()
        self.stop = False
        self.actors = {}
        self.box_app = None
        self.counters = {"confirmed": 0, "rejected": 0, "unexpected": 0, "submit_divergence": 0}
        self.op_counts = {}
        self.scenario_counts = {}
        self.scenario = "setup"

    # -- recording ------------------------------------------------------

    def emit(self, rec):
        self.out.write(json.dumps(rec, sort_keys=True) + "\n")
        self.out.flush()

    def record_step(self, op, outcome, expect, parsed, detail, submissions=None):
        self.seq += 1
        ok = outcome == expect
        self.counters[outcome] = self.counters.get(outcome, 0) + 1
        if not ok:
            self.counters["unexpected"] += 1
        self.op_counts[op] = self.op_counts.get(op, 0) + 1
        rec = {
            "kind": "workload_step",
            "seq": self.seq,
            "scenario": self.scenario,
            "op": op,
            "outcome": outcome,
            "expect": expect,
            "ok": ok,
            "txids": parsed.get("txids", []),
            "round": parsed.get("round"),
            "t_utc": utc_now(),
            "detail": detail[-400:],
        }
        if submissions is not None:
            rec["submissions"] = submissions
        self.emit(rec)
        return rec

    # -- primitives -----------------------------------------------------

    def should_stop(self):
        if self.stop:
            return True
        if self.duration_s and self.clock() - self.t0 >= self.duration_s:
            return True
        if self.rounds and self.start_round is not None:
            cur = self.env.current_round()
            if cur is not None and cur >= self.start_round + self.rounds - STOP_MARGIN_ROUNDS:
                return True
        return False

    def gate(self):
        """Called before every step: stop mid-scenario once the budget is
        spent, so the last step has committed (and been compared) before the
        soak ends.  Abandoning a scenario half way is harmless."""
        if self.should_stop():
            raise StopRequested()

    def note(self, op):
        return "w{}-{}".format(self.seq + 1, op)

    def run(self, op, args, expect="confirmed", must=False):
        """Run a goal command that submits one transaction and waits."""
        self.gate()
        rc, out = self.env.goal("{} --note {}".format(args, self.note(op)))
        parsed = parse_goal_output(out)
        outcome = "confirmed" if rc == 0 and parsed["round"] is not None else "rejected"
        rec = self.record_step(op, outcome, expect, parsed, out)
        if must and not rec["ok"]:
            raise ScenarioAbort("{} did not {}: {}".format(op, expect, out[-200:]))
        return parsed, rec

    def run_shell(self, op, cmd, expect="confirmed", must=False):
        """Run a multi-command shell pipeline (atomic group builds)."""
        self.gate()
        rc, out = self.env.sh(cmd)
        parsed = parse_goal_output(out)
        outcome = "confirmed" if rc == 0 and parsed["round"] is not None else "rejected"
        rec = self.record_step(op, outcome, expect, parsed, out)
        if must and not rec["ok"]:
            raise ScenarioAbort("{} did not {}: {}".format(op, expect, out[-200:]))
        return parsed, rec

    def negative(self, op, build_cmd, out_file):
        """Build a signed txn (or group) in the container and submit it to a
        Go node and the Rust node.  Both must reject it."""
        self.gate()
        rc, out = self.env.sh(build_cmd)
        if rc != 0:
            # The build/sign command itself failed (kmd down, bad flag, ...):
            # nothing was submitted, so this is NOT evidence that both nodes
            # reject the transaction.  Record a failed step with the output.
            self.record_step(op, "error", "rejected", {}, "build/sign failed (rc={}): {}".format(rc, out),
                             submissions=[])
            return
        rc, b64 = self.env.fetch_file_b64(out_file)
        if rc != 0 or not b64:
            raise ScenarioAbort("could not read " + out_file)
        raw = base64.b64decode(b64)
        subs = []
        for node in NEGATIVE_TARGETS:
            status, body = self.env.post_txn(node, raw)
            subs.append({"node": node, "status": status, "body": body[-160:]})
        rejected = [s["status"] != 200 and s["status"] != 0 for s in subs]
        connect_err = any(s["status"] == 0 for s in subs)
        outcome = "rejected" if all(rejected) else "confirmed"
        rec = self.record_step(op, outcome, "rejected", {}, json.dumps(subs), submissions=subs)
        if connect_err or any(rejected) != all(rejected):
            self.counters["submit_divergence"] += 1
            rec["submit_divergence"] = True
            self.emit({
                "kind": "workload_divergence",
                "seq": rec["seq"],
                "op": op,
                "submissions": subs,
            })

    def goal_must(self, args):
        rc, out = self.env.goal(args)
        if rc != 0:
            diag = ""
            if "wallet" in out or "kmd" in out:
                _, d = self.env.sh("ls -ld {0}/kmd-v0.5; id; tail -n 5 {0}/kmd-v0.5/kmd.log {0}/kmd-v0.5/kmd-err.log".format(DATA_DIR))
                diag = " | kmd diag: " + d.replace("\n", " ")[-400:]
            raise ScenarioAbort("goal {} failed: {}{}".format(args, out[-200:], diag))
        return out

    def new_account(self):
        out = self.goal_must("account new")
        m = NEW_ACCOUNT_RE.search(out) or ADDR_RE.search(out)
        if not m:
            raise ScenarioAbort("no address in: " + out)
        return m.group(1) if m.re is NEW_ACCOUNT_RE else m.group(0)

    def account_info(self, addr):
        return self.env.rest_json("/v2/accounts/{}".format(addr))

    def fund(self, addr, amount):
        self.run("fund", "clerk send -f {} -t {} -a {}".format(self.funder, addr, amount), must=True)

    def ensure_balance(self, addr, minimum):
        """Make sure `addr` can spend at least `minimum` microAlgos (balance
        above its own minimum balance, which grows with apps/assets held)."""
        try:
            info = self.account_info(addr)
            spendable = int(info["amount"]) - int(info.get("min-balance", 0))
        except Exception:
            spendable = 0
        if spendable < minimum:
            self.fund(addr, minimum - spendable + 1000000)

    def newest_created(self, addr, key, idkey):
        info = self.account_info(addr)
        ids = [int(x[idkey]) for x in info.get(key, [])]
        if not ids:
            raise ScenarioAbort("{} has no {}".format(addr, key))
        return max(ids)

    def warm_kmd(self):
        """Start a persistent kmd and wait until it lists wallets.  The first
        goal call on a cold node has been seen to hit "connection refused"
        on 127.0.0.1:7833 (CI run 37911992082), so do not rely on goal's
        implicit start.  Tries root, then the image's own user."""
        last = ""
        for user in getattr(self.env, "users", ("root", "algorand")):
            if hasattr(self.env, "user"):
                self.env.user = user
            for attempt in range(8):
                self.env.goal("kmd start -t 0")
                rc, out = self.env.goal("wallet list")
                last = out
                if rc == 0:
                    self.emit({"kind": "workload_kmd", "user": user, "attempts": attempt + 1, "t_utc": utc_now()})
                    return
                self.env.sleep(5)
        raise ScenarioAbort("kmd never became ready: " + last[-300:])

    # -- setup ----------------------------------------------------------

    def setup(self):
        self.scenario = "setup"
        self.start_round = self.env.current_round()
        # start.sh makes netroot/ a+rwX so host readers work, but kmd refuses
        # to start on a world-writable data dir ("too permissive (777)").
        rc, out = self.env.sh("chmod 700 {}/kmd-v0.5; mkdir -p {}".format(DATA_DIR, WORK_DIR))
        if rc != 0:
            raise SystemExit("cannot create {} in container: {}".format(WORK_DIR, out))
        self.warm_kmd()
        for name in ("rich_app.teal", "rich_clear.teal"):
            self.env.put_file(os.path.join(WORKLOAD_DIR, name), "{}/{}".format(WORK_DIR, name))
        if not self.funder:
            rc, out = self.env.goal("account list")
            m = ADDR_RE.search(out)
            if not m:
                raise SystemExit("cannot discover funder account: " + out)
            self.funder = m.group(0)
        for name in ("A", "B", "C", "D"):
            addr = self.new_account()
            self.actors[name] = addr
            self.fund(addr, 50000000)
        self.emit({
            "kind": "workload_meta",
            "version": 1,
            "seed": self.seed,
            "funder": self.funder,
            "actors": self.actors,
            "start_round": self.start_round,
            "t_utc": utc_now(),
        })

    # -- scenarios ------------------------------------------------------

    def sc_pay(self):
        a, b = self.rng.sample(sorted(self.actors), 2)
        amt = self.rng.randint(1, 5000000)
        self.run("pay", "clerk send -f {} -t {} -a {}".format(self.actors[a], self.actors[b], amt), must=True)
        if self.rng.random() < 0.5:
            self.run(
                "pay_zero_self",
                "clerk send -f {0} -t {0} -a 0".format(self.actors[a]),
            )

    def sc_min_balance(self):
        d, b = self.actors["D"], self.actors["B"]
        self.ensure_balance(d, 1000000)
        info = self.account_info(d)
        amount, minbal = int(info["amount"]), int(info["min-balance"])
        spend = amount - minbal - 1000
        if spend <= 0:
            raise ScenarioAbort("D is below min balance + fee")
        # A payment that leaves the sender at exactly the minimum balance.
        self.run("pay_exact_min_balance", "clerk send -f {} -t {} -a {}".format(d, b, spend), must=True)
        # One more microAlgo cannot be spent: balance would drop below min.
        self.negative(
            "pay_below_min_balance",
            "cd {w} && goal clerk send -f {d} -t {b} -a 1 -s -o neg.stxn -d {dd} 2>&1".format(
                w=WORK_DIR, d=d, b=b, dd=DATA_DIR
            ),
            WORK_DIR + "/neg.stxn",
        )
        self.run("fund", "clerk send -f {} -t {} -a 5000000".format(self.funder, d), must=True)

    def sc_asset(self):
        a, b, c, d = (self.actors[k] for k in "ABCD")
        self.ensure_balance(a, 5000000)
        self.ensure_balance(b, 3000000)
        self.ensure_balance(c, 3000000)
        parsed, _ = self.run(
            "asset_create",
            "asset create --creator {a} --total 1000000 --decimals 0 --unitname WL --name workload-asset "
            "--manager {a} --freezer {a} --clawback {a}".format(a=a),
            must=True,
        )
        aid = parsed["asset_id"]
        if aid is None:
            raise ScenarioAbort("asset id not parsed")
        self.run("asset_optin", "asset optin --assetid {} --account {}".format(aid, b), must=True)
        self.run("asset_optin", "asset optin --assetid {} --account {}".format(aid, c), must=True)
        self.run("asset_send", "asset send --assetid {} --from {} --to {} --amount 500".format(aid, a, b), must=True)
        self.run("asset_send", "asset send --assetid {} --from {} --to {} --amount 300".format(aid, a, c), must=True)
        # Closing the Algo account of a holder of assets must fail on both.
        self.negative(
            "close_account_with_assets",
            "cd {w} && goal clerk send -f {b} -t {d} -a 0 --close-to {d} -s -o neg.stxn -d {dd} 2>&1".format(
                w=WORK_DIR, b=b, d=d, dd=DATA_DIR
            ),
            WORK_DIR + "/neg.stxn",
        )
        # Frozen holding cannot send.
        self.run("asset_freeze", "asset freeze --assetid {} --freezer {} --account {} --freeze=true".format(aid, a, b), must=True)
        self.run(
            "asset_send_frozen",
            "asset send --assetid {} --from {} --to {} --amount 1".format(aid, b, c),
            expect="rejected",
        )
        self.run("asset_unfreeze", "asset freeze --assetid {} --freezer {} --account {} --freeze=false".format(aid, a, b), must=True)
        self.run(
            "asset_clawback",
            "asset send --assetid {} --clawback {} --from {} --to {} --amount 100".format(aid, a, c, a),
            must=True,
        )
        # Close the asset holdings out to the creator, then destroy.
        self.run("asset_close_out", "asset send --assetid {} --from {} --to {} --amount 0 --close-to {}".format(aid, b, a, a), must=True)
        self.run("asset_close_out", "asset send --assetid {} --from {} --to {} --amount 0 --close-to {}".format(aid, c, a, a), must=True)
        self.run("asset_destroy", "asset destroy --assetid {} --creator {}".format(aid, a), must=True)

    def create_rich_app(self, creator, tag):
        parsed, _ = self.run(
            "app_create",
            "app create --creator {} --approval-prog {w}/rich_app.teal --clear-prog {w}/rich_clear.teal "
            "--global-ints 2 --global-byteslices 1 --local-ints 2 --local-byteslices 1 --fee 2000".format(
                creator, w=WORK_DIR
            ),
            must=True,
        )
        if parsed["app_id"] is None:
            raise ScenarioAbort("app id not parsed")
        return parsed["app_id"]

    def app_call(self, op, app_id, sender, args, extra="", expect="confirmed", fee=2000):
        arg_s = " ".join("--app-arg {}".format(a) for a in args)
        return self.run(
            op,
            "app call --app-id {} --from {} {} {} --fee {}".format(app_id, sender, arg_s, extra, fee),
            expect=expect,
            must=(expect == "confirmed"),
        )

    def sc_app_boxes(self):
        a = self.actors["A"]
        self.ensure_balance(a, 10000000)
        app = self.create_rich_app(a, "boxes")
        self.box_app = app
        self.fund_app(app, 2500000)
        n1, n2 = "bx{}".format(self.rng.randint(10, 99)), "by{}".format(self.rng.randint(10, 99))
        size = self.rng.randint(32, 200)
        box = lambda n: "--box str:{}".format(n)  # noqa: E731
        self.app_call("box_put", app, a, ["str:bput", "str:" + n2, "str:" + "x" * 40], box(n2))
        self.app_call("box_create", app, a, ["str:bcreate", "str:" + n1, "int:{}".format(size)], box(n1))
        self.app_call("box_get", app, a, ["str:bget", "str:" + n1], box(n1))
        self.app_call("box_extract", app, a, ["str:bext", "str:" + n2, "int:10"], box(n2))
        self.app_call("box_replace", app, a, ["str:brepl", "str:" + n2, "str:12345678"], box(n2))
        self.app_call("box_splice", app, a, ["str:bsplice", "str:" + n2, "str:Z"], box(n2))
        self.app_call("box_resize", app, a, ["str:bresize", "str:" + n1, "int:{}".format(size + 100)], box(n1))
        self.app_call("gput", app, a, ["str:gput", "int:77"])
        self.app_call("log", app, a, ["str:log", "str:hello-workload"])
        # Negative: reading a box that does not exist trips an assert.
        self.app_call("box_get_missing", app, a, ["str:bget", "str:nobox"], box("nobox"), expect="rejected")
        # Negative: a box whose min balance the app account cannot cover.
        self.app_call(
            "box_create_unfunded",
            app,
            a,
            ["str:bcreate", "str:huge", "int:8180"],
            box("huge") + " --empty-refs 6",
            expect="rejected",
            fee=2000,
        )
        self.app_call("box_delete", app, a, ["str:bdel", "str:" + n2], box(n2))
        # Delete the app while box n1 still exists (the box is orphaned).
        self.run("app_delete", "app delete --app-id {} --from {}".format(app, a), must=True)

    def fund_app(self, app, amount):
        self.run("fund_app", "clerk send -f {} -t {} -a {}".format(self.funder, app_address(app), amount), must=True)

    def sc_app_inner(self):
        a, b, c = self.actors["A"], self.actors["B"], self.actors["C"]
        self.ensure_balance(a, 10000000)
        self.ensure_balance(b, 5000000)
        app = self.create_rich_app(a, "inner")
        addr = app_address(app)
        self.fund_app(app, 8000000)
        fee = 8000
        self.app_call("inner_pay", app, a, ["str:ipay", "int:123456"], "--app-account {}".format(b), fee=fee)
        self.app_call("inner_asset_create", app, a, ["str:iasset"], "", fee=fee)
        inner_asset = self.newest_created(addr, "created-assets", "index")
        # B opts in, the app sends part of its inner asset.
        self.run("asset_optin", "asset optin --assetid {} --account {}".format(inner_asset, b), must=True)
        self.app_call(
            "inner_asset_send",
            app,
            a,
            ["str:isend", "int:100"],
            "--foreign-asset {} --app-account {}".format(inner_asset, b),
            fee=fee,
        )
        # A second asset, opted into by the app, funded by A, then closed out.
        parsed, _ = self.run(
            "asset_create",
            "asset create --creator {a} --total 5000 --decimals 0 --unitname W2 --name workload-two".format(a=a),
            must=True,
        )
        a2 = parsed["asset_id"]
        self.app_call("inner_asset_optin", app, a, ["str:iopt"], "--foreign-asset {}".format(a2), fee=fee)
        self.run("asset_send", "asset send --assetid {} --from {} --to {} --amount 50".format(a2, a, addr), must=True)
        self.app_call(
            "inner_asset_send",
            app,
            a,
            ["str:isend", "int:20"],
            "--foreign-asset {} --app-account {}".format(a2, a),
            fee=fee,
        )
        self.app_call(
            "inner_asset_close",
            app,
            a,
            ["str:iaclose"],
            "--foreign-asset {} --app-account {}".format(a2, a),
            fee=fee,
        )
        # Inner application create, call, delete.
        self.app_call("inner_app_create", app, a, ["str:iappl"], "", fee=fee)
        child = self.newest_created(addr, "created-apps", "id")
        self.app_call("inner_app_call", app, a, ["str:icall"], "--foreign-app {}".format(child), fee=fee)
        self.app_call("inner_app_delete", app, a, ["str:idel"], "--foreign-app {}".format(child), fee=fee)
        # The app account still holds the inner asset it created, so
        # closing it through the delete path must be rejected everywhere.
        close_neg = (
            "cd {w} && goal app delete --app-id {app} --from {a} --app-arg str:closedel --app-account {c} "
            "--fee 4000 -s -o neg.stxn -d {dd} 2>&1".format(w=WORK_DIR, app=app, a=a, c=c, dd=DATA_DIR)
        )
        self.negative("app_close_with_assets", close_neg, WORK_DIR + "/neg.stxn")
        # Give the inner asset back, destroy it from inside the app, and
        # then the same delete closes the (now empty) app account for real.
        self.run(
            "asset_close_out",
            "asset send --assetid {} --from {} --to {} --amount 0 --close-to {}".format(inner_asset, b, addr, addr),
            must=True,
        )
        self.app_call("inner_asset_destroy", app, a, ["str:idestroy"], "--foreign-asset {}".format(inner_asset), fee=fee)
        self.run(
            "app_delete_close_account",
            "app delete --app-id {} --from {} --app-arg str:closedel --app-account {} --fee 4000".format(app, a, c),
            must=True,
        )

    def sc_app_close_delete(self):
        a, b = self.actors["A"], self.actors["B"]
        self.ensure_balance(a, 10000000)
        app = self.create_rich_app(a, "closedel")
        self.fund_app(app, 3000000)
        # Delete the app and close its account into B via an inner payment
        # with close_remainder_to in the same transaction.
        self.run(
            "app_delete_close_account",
            "app delete --app-id {} --from {} --app-arg str:closedel --app-account {} --fee 4000".format(app, a, b),
            must=True,
        )

    def sc_app_local(self):
        a, b = self.actors["A"], self.actors["B"]
        self.ensure_balance(a, 10000000)
        self.ensure_balance(b, 5000000)
        app = self.create_rich_app(a, "local")
        self.run("app_optin", "app optin --app-id {} --from {}".format(app, b), must=True)
        self.app_call("local_put", app, b, ["str:lput", "int:7"])
        self.run("app_closeout", "app closeout --app-id {} --from {}".format(app, b), must=True)
        self.run("app_optin", "app optin --app-id {} --from {}".format(app, b), must=True)
        self.run("app_clear", "app clear --app-id {} --from {}".format(app, b), must=True)
        self.run("app_delete", "app delete --app-id {} --from {}".format(app, a), must=True)

    def group_cmd(self, members, final):
        """Shell pipeline: build every member, group, sign, then `final`."""
        parts = ["cd {}".format(WORK_DIR)]
        files = []
        for i, args in enumerate(members):
            fn = "g{}.txn".format(i)
            files.append(fn)
            parts.append("goal {} -o {} -d {} --note {}".format(args, fn, DATA_DIR, self.note("g{}".format(i))))
        parts.append("cat {} > gc.txn".format(" ".join(files)))
        parts.append("goal clerk group -i gc.txn -o gg.txn -d {}".format(DATA_DIR))
        parts.append("goal clerk sign -i gg.txn -o gs.stxn -d {}".format(DATA_DIR))
        parts.append(final)
        return " && ".join(parts) + " 2>&1"

    def sc_group(self):
        a, b, c, d = (self.actors[k] for k in "ABCD")
        for x in (a, b, c):
            self.ensure_balance(x, 5000000)
        rawsend = "goal clerk rawsend -f gs.stxn -d {}".format(DATA_DIR)
        ring = [
            "clerk send -f {} -t {} -a {}".format(a, b, self.rng.randint(1000, 90000)),
            "clerk send -f {} -t {} -a {}".format(b, c, self.rng.randint(1000, 90000)),
            "clerk send -f {} -t {} -a {}".format(c, a, self.rng.randint(1000, 90000)),
        ]
        self.run_shell("group_pay_ring", self.group_cmd(ring, rawsend), must=True)
        if self.box_app is not None:
            # Payment + app call that touches a box, if the box app still
            # exists.  The app was deleted at the end of sc_app_boxes, so
            # this is a call to a deleted app and must be rejected.
            mixed = [
                "clerk send -f {} -t {} -a 1000".format(a, d),
                "app call --app-id {} --from {} --app-arg str:bput --app-arg str:gx --app-arg str:yy "
                "--box str:gx --fee 2000".format(self.box_app, a),
            ]
            self.negative(
                "group_call_deleted_app",
                self.group_cmd(mixed, "true"),
                WORK_DIR + "/gs.stxn",
            )
        # An atomic group with one failing member is rejected as a whole.
        bad = [
            "clerk send -f {} -t {} -a 1000".format(a, b),
            "clerk send -f {} -t {} -a 900000000000000".format(d, b),
        ]
        self.negative("group_one_member_overspends", self.group_cmd(bad, "true"), WORK_DIR + "/gs.stxn")

    def sc_account_close(self):
        x = self.new_account()
        b = self.actors["B"]
        self.fund(x, 2000000)
        self.run("account_close", "clerk send -f {} -t {} -a 0 --close-to {}".format(x, b, b), must=True)
        self.run("send_from_closed_account", "clerk send -f {} -t {} -a 1".format(x, b), expect="rejected")

    SCENARIOS = {
        "pay": sc_pay,
        "min_balance": sc_min_balance,
        "asset": sc_asset,
        "app_boxes": sc_app_boxes,
        "app_inner": sc_app_inner,
        "app_local": sc_app_local,
        "group": sc_group,
        "account_close": sc_account_close,
        "app_close_delete": sc_app_close_delete,
    }

    # -- driver ---------------------------------------------------------

    def plan(self, count):
        """The scenario names this seed will run, in order (pure function)."""
        rng = random.Random(self.seed ^ 0x5EED)
        names = list(self.only or SCENARIO_ORDER)
        pool = sorted(self.only or SCENARIO_WEIGHTS)
        weights = [SCENARIO_WEIGHTS.get(n, 1) for n in pool]
        while len(names) < count:
            names.append(rng.choices(pool, weights)[0])
        return names[:count]

    def abort(self, scenario, reason, exception=False):
        self.emit({"kind": "workload_abort", "scenario": scenario, "reason": reason[:600],
                   "exception": exception, "t_utc": utc_now()})

    def run_all(self):
        """Run until the budget is spent.  Returns the process exit status:
        2 if setup failed (kmd never ready, funding failed, ...), else 0.
        A workload_summary is always written."""
        try:
            self.setup()
        except StopRequested:
            self.finish()
            return 0
        except (ScenarioAbort, SystemExit) as e:
            self.abort("setup", str(e))
            self.finish()
            return 2
        except Exception as e:  # noqa: BLE001 - REST/JSON/OS errors must not kill the run silently
            self.abort("setup", "unexpected {}: {}".format(type(e).__name__, e), exception=True)
            self.finish()
            return 2
        i = 0
        while not self.should_stop():
            name = self.plan(i + 1)[i]
            self.scenario = name
            self.scenario_counts[name] = self.scenario_counts.get(name, 0) + 1
            try:
                Workload.SCENARIOS[name](self)
            except StopRequested:
                break
            except ScenarioAbort as e:
                self.abort(name, str(e))
                self.env.sleep(2)
            except Exception as e:  # noqa: BLE001 - e.g. URLError / KeyError from REST helpers
                reason = "unexpected {}: {}".format(type(e).__name__, e)
                # A failed step so the analyzer cannot count this as success.
                self.record_step("exception:" + name, "error", "confirmed", {}, reason)
                self.abort(name, reason, exception=True)
                self.env.sleep(2)
            i += 1
        self.finish()
        return 0

    def finish(self):
        try:
            end_round = self.env.current_round()
        except Exception:  # noqa: BLE001 - the summary must always be written
            end_round = None
        self.emit({
            "kind": "workload_summary",
            "seed": self.seed,
            "steps": self.seq,
            "confirmed": self.counters.get("confirmed", 0),
            "rejected": self.counters.get("rejected", 0),
            "unexpected": self.counters["unexpected"],
            "submit_divergence": self.counters["submit_divergence"],
            "op_counts": self.op_counts,
            "scenario_counts": self.scenario_counts,
            "start_round": self.start_round,
            "end_round": end_round,
            "t_utc": utc_now(),
        })


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--out", required=True, help="Output JSONL path.")
    ap.add_argument("--seed", type=int, default=int(os.environ.get("WORKLOAD_SEED", "1674")))
    ap.add_argument("--rounds", type=int, default=0, help="Stop after N rounds past the start round.")
    ap.add_argument("--duration-s", type=int, default=0, help="Stop after S wall-clock seconds.")
    ap.add_argument("--genesis", default=os.path.join(ROOT, "netroot", "genesis.json"))
    ap.add_argument("--wallet", default=None, help="kmd wallet name, if the node has several.")
    ap.add_argument("--scenarios", default=os.environ.get("WORKLOAD_SCENARIOS", ""),
                    help="Comma list restricting the scenarios (default: all, see SCENARIO_ORDER).")
    ap.add_argument("--print-plan", type=int, default=0, metavar="N", help="Print the first N scenarios and exit.")
    args = ap.parse_args()

    only = [x for x in args.scenarios.split(",") if x]
    unknown = [x for x in only if x not in SCENARIO_WEIGHTS]
    if unknown:
        ap.error("unknown scenario(s): " + ",".join(unknown))

    if args.print_plan:
        w = Workload(None, None, args.seed, only=only)
        print("\n".join(w.plan(args.print_plan)))
        return 0

    env = Env(wallet=args.wallet)
    with open(args.out, "w", encoding="utf-8") as out:
        w = Workload(env, out, args.seed, args.rounds, args.duration_s, funder=genesis_funder(args.genesis),
                     only=only)

        def _stop(*_):
            w.stop = True

        signal.signal(signal.SIGTERM, _stop)
        signal.signal(signal.SIGINT, _stop)
        return w.run_all()


if __name__ == "__main__":
    sys.exit(main())
