[package]
name = "algo-conformance"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
algo-types.workspace = true
algo-codec.workspace = true
algo-error.workspace = true
algo-validate.workspace = true
algo-ledger.workspace = true
algo-rest-client.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
chrono.workspace = true
hex.workspace = true
serde_bytes.workspace = true

[dev-dependencies]
rmp-serde.workspace = true
algo-avm.workspace = true
serde.workspace = true
