// Copyright (C) 2019-2026 Algorand Foundation Ltd.
// Modifications Copyright (C) 2026 Algod DAO
// This file is part of algod-rust, a modified work based on go-algorand
// (https://github.com/algorand/go-algorand).
//
// algod-rust is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// algod-rust is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with algod-rust.  If not, see <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: AGPL-3.0-or-later

//! PQ private-key file format, mirroring `../go-algorand/cmd/algokey/pq_key.go`.
//!
//! `pqPublicMaterial`/`pqSigningMaterial` are Go's `codec`-tagged structs;
//! their msgpack encoding is generated by `msgp` (see `msgp_gen.go`) with
//! **unconditional** (no `omitempty`) fields in lexicographic key order:
//! `pqPublicMaterial{"public-key", "salt", "scheme"}` and
//! `pqSigningMaterial{"private-key", "public"}`. We reproduce those exact
//! bytes by hand (via `rmp::encode`/`rmp::decode`) so a keyfile generated by
//! this binary and by real `algokey pq generate` are interchangeable.

use std::path::Path;

use algo_types::{pq_address, Address, PQAddressSalt, PQ_SCHEME_FALCON1024};

use crate::common::write_with_mode_0600;

/// A PQ public key with its address salt (Go: `pqPublicMaterial`,
/// `pq_key.go:35-41`).
#[derive(Debug, Clone, PartialEq)]
pub struct PqPublicMaterial {
    pub scheme: [u8; 2],
    pub salt: PQAddressSalt,
    pub public_key: Vec<u8>,
}

impl PqPublicMaterial {
    /// Mirrors `pqPublicMaterial.address()` (`pq_key.go:43-45`).
    pub fn address(&self) -> Address {
        pq_address(self.scheme, self.salt, &self.public_key)
    }

    /// Mirrors `pqPublicMaterial.validate()` (`pq_key.go:47-59`).
    pub fn validate(&self) -> Result<(), String> {
        if self.scheme != PQ_SCHEME_FALCON1024 {
            return Err(format!(
                "pq scheme not supported: {:?}",
                String::from_utf8_lossy(&self.scheme)
            ));
        }
        if self.public_key.len() != algo_falcon::FALCON_DET1024_PUBKEY_SIZE {
            return Err(format!(
                "pq key file is malformed: got public key size {}, want {}",
                self.public_key.len(),
                algo_falcon::FALCON_DET1024_PUBKEY_SIZE
            ));
        }
        if !self.address().is_pq_compliant() {
            return Err(format!(
                "pq address salt is not compliant: address {}",
                self.address()
            ));
        }
        Ok(())
    }
}

/// A PQ private key with its public envelope (Go: `pqSigningMaterial`,
/// `pq_key.go:64-69`). Key files hold the scheme's working keys, never the
/// mnemonic entropy they were derived from.
#[derive(Debug, Clone, PartialEq)]
pub struct PqSigningMaterial {
    pub public: PqPublicMaterial,
    pub private_key: Vec<u8>,
}

impl PqSigningMaterial {
    /// Mirrors `pqSigningMaterial.validate()` (`pq_key.go:71-80`).
    pub fn validate(&self) -> Result<(), String> {
        self.public.validate()?;
        if self.private_key.len() != algo_falcon::FALCON_DET1024_PRIVKEY_SIZE {
            return Err(format!(
                "pq key file is malformed: got private key size {}, want {}",
                self.private_key.len(),
                algo_falcon::FALCON_DET1024_PRIVKEY_SIZE
            ));
        }
        Ok(())
    }
}

/// Encode a `PqSigningMaterial` exactly as Go's `protocol.Encode(&signing)`
/// would (`pq_key.go:82-87`): an unconditional, alphabetically key-ordered
/// msgpack map, nested one level for `public`.
pub fn encode_pq_signing_material(m: &PqSigningMaterial) -> Vec<u8> {
    let mut out = Vec::new();
    // pqSigningMaterial: {"private-key", "public"} (alphabetical).
    rmp::encode::write_map_len(&mut out, 2).unwrap();
    rmp::encode::write_str(&mut out, "private-key").unwrap();
    rmp::encode::write_bin(&mut out, &m.private_key).unwrap();
    rmp::encode::write_str(&mut out, "public").unwrap();
    encode_pq_public_material(&mut out, &m.public);
    out
}

fn encode_pq_public_material(out: &mut Vec<u8>, p: &PqPublicMaterial) {
    // pqPublicMaterial: {"public-key", "salt", "scheme"} (alphabetical).
    rmp::encode::write_map_len(out, 3).unwrap();
    rmp::encode::write_str(out, "public-key").unwrap();
    rmp::encode::write_bin(out, &p.public_key).unwrap();
    rmp::encode::write_str(out, "salt").unwrap();
    rmp::encode::write_uint(out, p.salt.0 as u64).unwrap();
    rmp::encode::write_str(out, "scheme").unwrap();
    rmp::encode::write_bin(out, &p.scheme).unwrap();
}

/// Decode a `PqSigningMaterial` previously produced by
/// [`encode_pq_signing_material`] (or by real go-algorand `algokey pq
/// generate`/`import`). Tolerant of map key order (reads by name, not
/// position) since msgpack maps aren't required to preserve encode order
/// on read, matching Go's `msgp`-generated unmarshal loop.
pub fn decode_pq_signing_material(data: &[u8]) -> Result<PqSigningMaterial, String> {
    let mut cur = data;
    let len = rmp::decode::read_map_len(&mut cur)
        .map_err(|e| format!("pq key file is malformed: {e}"))?;
    let mut private_key: Option<Vec<u8>> = None;
    let mut public: Option<PqPublicMaterial> = None;
    for _ in 0..len {
        let key = read_str(&mut cur)?;
        match key.as_str() {
            "private-key" => private_key = Some(read_bin(&mut cur)?),
            "public" => public = Some(decode_pq_public_material(&mut cur)?),
            _ => skip_value(&mut cur)?,
        }
    }
    Ok(PqSigningMaterial {
        public: public.ok_or("pq key file is malformed: missing \"public\" field")?,
        private_key: private_key
            .ok_or("pq key file is malformed: missing \"private-key\" field")?,
    })
}

fn decode_pq_public_material(cur: &mut &[u8]) -> Result<PqPublicMaterial, String> {
    let len =
        rmp::decode::read_map_len(cur).map_err(|e| format!("pq key file is malformed: {e}"))?;
    let mut public_key: Option<Vec<u8>> = None;
    let mut salt: Option<u8> = None;
    let mut scheme: Option<[u8; 2]> = None;
    for _ in 0..len {
        let key = read_str(cur)?;
        match key.as_str() {
            "public-key" => public_key = Some(read_bin(cur)?),
            "salt" => {
                salt = Some(
                    rmp::decode::read_int(cur)
                        .map_err(|e| format!("pq key file is malformed: {e}"))?,
                )
            }
            "scheme" => {
                let bytes = read_bin(cur)?;
                if bytes.len() != 2 {
                    return Err(format!(
                        "pq key file is malformed: scheme field is {} bytes, want 2",
                        bytes.len()
                    ));
                }
                scheme = Some([bytes[0], bytes[1]]);
            }
            _ => skip_value(cur)?,
        }
    }
    Ok(PqPublicMaterial {
        scheme: scheme.ok_or("pq key file is malformed: missing \"scheme\" field")?,
        salt: PQAddressSalt(salt.ok_or("pq key file is malformed: missing \"salt\" field")?),
        public_key: public_key.ok_or("pq key file is malformed: missing \"public-key\" field")?,
    })
}

fn read_str(cur: &mut &[u8]) -> Result<String, String> {
    rmp::decode::read_str_from_slice(*cur)
        .map(|(s, rest)| {
            let owned = s.to_string();
            *cur = rest;
            owned
        })
        .map_err(|e| format!("pq key file is malformed: {e:?}"))
}

fn read_bin(cur: &mut &[u8]) -> Result<Vec<u8>, String> {
    let len =
        rmp::decode::read_bin_len(cur).map_err(|e| format!("pq key file is malformed: {e}"))?;
    let len = len as usize;
    if cur.len() < len {
        return Err("pq key file is malformed: truncated binary field".to_string());
    }
    let (bytes, rest) = cur.split_at(len);
    *cur = rest;
    Ok(bytes.to_vec())
}

/// Skip one arbitrary scalar/string/binary msgpack value (used to tolerate
/// unknown fields, as `msgp`-generated decoders do). The pq key file format
/// only ever nests one level (handled explicitly by the caller before
/// falling through to this), so only leaf marker kinds need handling.
fn skip_value(cur: &mut &[u8]) -> Result<(), String> {
    use rmp::Marker;
    let marker = rmp::decode::read_marker(cur).map_err(|e| format!("{e:?}"))?;
    match marker {
        Marker::FixPos(_) | Marker::FixNeg(_) | Marker::Null | Marker::True | Marker::False => {
            Ok(())
        }
        Marker::U8 | Marker::I8 => skip_bytes(cur, 1),
        Marker::U16 | Marker::I16 => skip_bytes(cur, 2),
        Marker::U32 | Marker::I32 | Marker::F32 => skip_bytes(cur, 4),
        Marker::U64 | Marker::I64 | Marker::F64 => skip_bytes(cur, 8),
        Marker::FixStr(n) => skip_bytes(cur, n as usize),
        Marker::Str8 | Marker::Bin8 => {
            let n = read_u8(cur)?;
            skip_bytes(cur, n as usize)
        }
        Marker::Str16 | Marker::Bin16 => {
            let n = read_u16(cur)?;
            skip_bytes(cur, n as usize)
        }
        Marker::Str32 | Marker::Bin32 => {
            let n = read_u32(cur)?;
            skip_bytes(cur, n as usize)
        }
        _ => Err("pq key file is malformed: unsupported field type".to_string()),
    }
}

fn read_u8(cur: &mut &[u8]) -> Result<u8, String> {
    if cur.is_empty() {
        return Err("pq key file is malformed: truncated field".to_string());
    }
    let v = cur[0];
    *cur = &cur[1..];
    Ok(v)
}

fn read_u16(cur: &mut &[u8]) -> Result<u16, String> {
    if cur.len() < 2 {
        return Err("pq key file is malformed: truncated field".to_string());
    }
    let v = u16::from_be_bytes([cur[0], cur[1]]);
    *cur = &cur[2..];
    Ok(v)
}

fn read_u32(cur: &mut &[u8]) -> Result<u32, String> {
    if cur.len() < 4 {
        return Err("pq key file is malformed: truncated field".to_string());
    }
    let v = u32::from_be_bytes([cur[0], cur[1], cur[2], cur[3]]);
    *cur = &cur[4..];
    Ok(v)
}

fn skip_bytes(cur: &mut &[u8], n: usize) -> Result<(), String> {
    if cur.len() < n {
        return Err("pq key file is malformed: truncated field".to_string());
    }
    *cur = &cur[n..];
    Ok(())
}

/// Write a private key file at mode 0600 (Go: `writePQPrivateKeyFile`,
/// `pq_key.go:82-87`).
pub fn write_pq_private_key_file(path: &Path, signing: &PqSigningMaterial) -> std::io::Result<()> {
    write_with_mode_0600(path, &encode_pq_signing_material(signing))
}

/// Read and validate a PQ private key file (Go: `readPQSigningMaterial` +
/// `decodePQPrivateKeyFileBytes`, `pq_key.go:89-106`).
pub fn read_pq_signing_material(path: &Path) -> Result<PqSigningMaterial, String> {
    let data = std::fs::read(path)
        .map_err(|e| format!("cannot read private key from {}: {e}", path.display()))?;
    let signing = decode_pq_signing_material(&data)?;
    signing.validate()?;
    Ok(signing)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Builds a `PqSigningMaterial` with a real *canonical* (PQ-compliant)
    /// salt for the given public key pattern — `salt` is ignored other than
    /// as documentation of intent; the actual salt is computed via
    /// `canonical_pq_address_salt` so `validate()` passes.
    fn sample(scheme: [u8; 2], _salt: u8, pk_byte: u8, sk_byte: u8) -> PqSigningMaterial {
        let public_key = vec![pk_byte; algo_falcon::FALCON_DET1024_PUBKEY_SIZE];
        let (salt, _addr) = algo_types::canonical_pq_address_salt(scheme, &public_key)
            .expect("a compliant salt must exist");
        PqSigningMaterial {
            public: PqPublicMaterial {
                scheme,
                salt,
                public_key,
            },
            private_key: vec![sk_byte; algo_falcon::FALCON_DET1024_PRIVKEY_SIZE],
        }
    }

    #[test]
    fn encode_matches_go_field_order_and_headers() {
        let m = sample(PQ_SCHEME_FALCON1024, 3, 0x11, 0x22);
        let bytes = encode_pq_signing_material(&m);
        // Outer map header: fixmap with 2 entries = 0x82.
        assert_eq!(bytes[0], 0x82);
        // First key: "private-key" (11 chars) -> fixstr 0xab.
        assert_eq!(bytes[1], 0xab);
        assert_eq!(&bytes[2..13], b"private-key");
    }

    #[test]
    fn encode_decode_round_trips() {
        let m = sample(PQ_SCHEME_FALCON1024, 7, 0xAB, 0xCD);
        let bytes = encode_pq_signing_material(&m);
        let decoded = decode_pq_signing_material(&bytes).expect("decode");
        assert_eq!(decoded, m);
    }

    #[test]
    fn validate_rejects_wrong_sized_public_key() {
        let mut m = sample(PQ_SCHEME_FALCON1024, 7, 1, 1);
        m.public.public_key.truncate(10);
        let err = m.validate().unwrap_err();
        assert!(err.contains("malformed"), "{err}");
    }

    #[test]
    fn validate_rejects_wrong_sized_private_key() {
        let mut m = sample(PQ_SCHEME_FALCON1024, 7, 1, 1);
        m.private_key.truncate(10);
        let err = m.validate().unwrap_err();
        assert!(err.contains("malformed"), "{err}");
    }

    #[test]
    fn validate_rejects_non_compliant_salt() {
        // Salt 0 with an all-zero-ish public key is extremely unlikely to be
        // PQ-compliant for an arbitrary fixed pattern chosen without
        // searching for compliance; assert validate() actually runs the
        // compliance check by picking a public key/salt pair known NOT to
        // satisfy it (probability of false failure here is negligible).
        let pk = vec![0x01u8; algo_falcon::FALCON_DET1024_PUBKEY_SIZE];
        // Find a salt that is NOT canonical for this pk (any salt other
        // than the returned canonical one will not be the *lowest*
        // compliant salt, but might still itself be compliant by chance;
        // to make this deterministic, use a salt whose derived address we
        // independently know is not PQ-compliant by scanning for one).
        let mut bad_salt = None;
        for s in 0..=255u8 {
            let addr = pq_address(PQ_SCHEME_FALCON1024, PQAddressSalt(s), &pk);
            if !addr.is_pq_compliant() {
                bad_salt = Some(s);
                break;
            }
        }
        let bad_salt = bad_salt.expect("at least one non-compliant salt must exist");
        let m = PqSigningMaterial {
            public: PqPublicMaterial {
                scheme: PQ_SCHEME_FALCON1024,
                salt: PQAddressSalt(bad_salt),
                public_key: pk,
            },
            private_key: vec![1u8; algo_falcon::FALCON_DET1024_PRIVKEY_SIZE],
        };
        let err = m.validate().unwrap_err();
        assert!(err.contains("not compliant"), "{err}");
    }

    #[test]
    fn write_then_read_round_trips_through_disk() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("pqkey");
        let m = sample(PQ_SCHEME_FALCON1024, 7, 0x33, 0x44);
        write_pq_private_key_file(&path, &m).unwrap();
        let read_back = read_pq_signing_material(&path).unwrap();
        assert_eq!(read_back, m);
    }
}
