[package]
name = "algokey-rust"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "algokey-rust"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
algo-codec.workspace = true
algo-consensus-crypto.workspace = true
algo-ledger.workspace = true
algo-types.workspace = true
ed25519-dalek.workspace = true
rand.workspace = true
rmp-serde = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
hex.workspace = true
tempfile = "3"
data-encoding = { workspace = true }
