#![no_main]

//! Fuzz target for AVM TEAL program parsing and execution.
//!
//! Uses `arbitrary` for structured program generation: valid version headers,
//! intcblock/bytecblock preambles, valid branch targets, and a mix of
//! pure opcodes. Falls back to raw byte fuzzing when structured generation
//! fails.
//!
//! Invariant: **no panics**. Any error return is acceptable.

use arbitrary::{Arbitrary, Unstructured};
use libfuzzer_sys::fuzz_target;

use algo_avm::opcode::Mode;
use algo_avm::{check_program, parse, AvmMachine, ExecMode, NullContext};

/// A structured TEAL program generated by the fuzzer.
#[derive(Debug)]
struct FuzzProgram {
    /// Raw bytecode including version header.
    bytes: Vec<u8>,
}

/// Opcodes that take no immediates, work in Any mode, and are available in v2+.
/// These are safe to emit without additional context.
const SIMPLE_OPCODES: &[u8] = &[
    0x08, // +
    0x09, // -
    0x0a, // /
    0x0b, // *
    0x0c, // <
    0x0d, // >
    0x0e, // <=
    0x0f, // >=
    0x10, // &&
    0x11, // ||
    0x12, // ==
    0x13, // !=
    0x14, // !
    0x15, // len
    0x16, // itob
    0x17, // btoi
    0x18, // %
    0x19, // |
    0x1a, // &
    0x1b, // ^
    0x1c, // ~
    0x1d, // mulw
    0x1e, // addw
    0x48, // pop
    0x49, // dup
    0x4a, // dup2
    0x4c, // swap
    0x4d, // select
    0x43, // return
    0x44, // assert
];

impl<'a> Arbitrary<'a> for FuzzProgram {
    fn arbitrary(u: &mut Unstructured<'a>) -> arbitrary::Result<Self> {
        let mut bytes = Vec::with_capacity(256);

        // Version byte: 1..=10 (stay within well-tested range)
        let version: u8 = u.int_in_range(2..=10)?;
        bytes.push(version);

        // --- intcblock preamble ---
        let num_ints: u8 = u.int_in_range(1..=4)?;
        bytes.push(0x20); // intcblock
        bytes.push(num_ints);
        for _ in 0..num_ints {
            // Small varuint values (single byte, no continuation)
            let val: u8 = u.arbitrary()?;
            bytes.push(val & 0x7f); // ensure high bit clear = single-byte varuint
        }

        // --- bytecblock preamble ---
        let num_bytes_entries: u8 = u.int_in_range(0..=3)?;
        bytes.push(0x26); // bytecblock
        bytes.push(num_bytes_entries);
        for _ in 0..num_bytes_entries {
            let blen: u8 = u.int_in_range(0..=8)?;
            bytes.push(blen);
            for _ in 0..blen {
                bytes.push(u.arbitrary()?);
            }
        }

        // --- instruction body ---
        let num_instructions: u8 = u.int_in_range(1..=40)?;

        // We will record branch instruction positions and patch them after.
        struct BranchPatch {
            offset: usize, // position of the int16 offset in `bytes`
        }
        let mut branch_patches: Vec<BranchPatch> = Vec::new();

        // Record instruction start offsets (relative to byte after version).
        let body_start = bytes.len();

        for _ in 0..num_instructions {
            let choice: u8 = u.int_in_range(0..=10)?;
            match choice {
                // Push an int constant reference
                0..=2 => {
                    let idx = u.int_in_range(0..=(num_ints.saturating_sub(1)))?;
                    if idx < 4 {
                        bytes.push(0x22 + idx); // intc_0..intc_3
                    } else {
                        bytes.push(0x21); // intc
                        bytes.push(idx);
                    }
                }
                // Push a byte constant reference
                3 => {
                    if num_bytes_entries > 0 {
                        let idx = u.int_in_range(0..=(num_bytes_entries.saturating_sub(1)))?;
                        if idx < 4 {
                            bytes.push(0x28 + idx); // bytec_0..bytec_3
                        } else {
                            bytes.push(0x27); // bytec
                            bytes.push(idx);
                        }
                    } else {
                        // No bytec entries, push an int instead
                        bytes.push(0x22); // intc_0
                    }
                }
                // pushint (inline varuint)
                4 => {
                    bytes.push(0x81); // pushint
                    let val: u8 = u.arbitrary()?;
                    bytes.push(val & 0x7f); // single-byte varuint
                }
                // pushbytes (inline bytes)
                5 => {
                    bytes.push(0x80); // pushbytes
                    let blen: u8 = u.int_in_range(0..=4)?;
                    bytes.push(blen);
                    for _ in 0..blen {
                        bytes.push(u.arbitrary()?);
                    }
                }
                // A simple no-immediate opcode
                6..=8 => {
                    let idx = u.choose_index(SIMPLE_OPCODES.len())?;
                    bytes.push(SIMPLE_OPCODES[idx]);
                }
                // Branch (b/bnz/bz) with placeholder offset — patched later
                9 => {
                    let branch_op = match u.int_in_range(0..=2)? {
                        0 => 0x40u8, // bnz
                        1 => 0x41,   // bz
                        _ => 0x42,   // b
                    };
                    bytes.push(branch_op);
                    branch_patches.push(BranchPatch {
                        offset: bytes.len(),
                    });
                    // Placeholder int16 (will be patched)
                    bytes.push(0);
                    bytes.push(0);
                }
                // store/load scratch
                _ => {
                    let slot: u8 = u.int_in_range(0..=15)?;
                    if u.arbitrary()? {
                        bytes.push(0x35); // store
                    } else {
                        bytes.push(0x34); // load
                    }
                    bytes.push(slot);
                }
            }
        }

        // --- Patch branch targets to point within the program body ---
        let body_len = bytes.len() - body_start;
        for patch in &branch_patches {
            // The branch offset is relative to the instruction AFTER the branch
            // (i.e., after the 3-byte branch instruction: opcode + int16).
            // The offset position in `bytes` is where the int16 starts.
            let after_branch = patch.offset + 2; // position after the branch instruction
            let after_branch_rel = after_branch - body_start;

            // Target: somewhere in [0, body_len). The offset is
            // target_rel - after_branch_rel (can be negative for backward jumps).
            // Clamp to valid range to avoid out-of-bounds.
            let target_rel = if body_len > 0 {
                // Pick a random target within the body
                let raw: u16 = u.arbitrary().unwrap_or(0);
                (raw as usize) % body_len
            } else {
                0
            };

            let offset_val = (target_rel as isize - after_branch_rel as isize) as i16;
            let offset_bytes = offset_val.to_be_bytes();
            bytes[patch.offset] = offset_bytes[0];
            bytes[patch.offset + 1] = offset_bytes[1];
        }

        Ok(FuzzProgram { bytes })
    }
}

fuzz_target!(|data: &[u8]| {
    // Strategy 1: Try structured generation from the fuzz input
    if let Ok(prog) = {
        let mut u = Unstructured::new(data);
        FuzzProgram::arbitrary(&mut u)
    } {
        run_program(&prog.bytes);
    }

    // Strategy 2: Also run the raw bytes directly (catches parser edge cases)
    run_program(data);
});

/// Parse, validate, and execute a TEAL program. Must not panic.
fn run_program(bytes: &[u8]) {
    // Try parsing
    let program = match parse(bytes) {
        Ok(p) => p,
        Err(_) => return,
    };

    // Try validating in both modes
    let _ = check_program(&program, Mode::Any, bytes.len(), 0);
    let _ = check_program(&program, Mode::LogicSig, bytes.len(), 0);
    let _ = check_program(&program, Mode::Application, bytes.len(), 0);

    // Try executing as LogicSig with limited budget
    let mut machine = AvmMachine::new(program.clone(), ExecMode::LogicSig, 20_000);
    let _ = machine.run(&mut NullContext);

    // Try executing as Application with limited budget
    let mut machine2 = AvmMachine::new(program, ExecMode::Application, 20_000);
    let _ = machine2.run(&mut NullContext);
}
